apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pypi-server
  name: pypi-server-packages
spec:
  storageClassName: openebs-jiva-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
