apiVersion: v1
kind: PersistentVolume
metadata:
  name: pypi-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-no-provisioner
  local:
    path: /mnt/glusterfs/kube-volumes/default_pypi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pi-k8s-1
          - pi-k8s-2
          - pi-k8s-3
