apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pypi-server
  name: pypi-server-packages
spec:
  storageClassName: local-storage-no-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
